<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
	    <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>	
	</head>
	
	<body class="yui-skin-sam">

        <div id="manager-top-bar-wrapper">
            <div style="opacity: 1;" id="manager-top-bar">
             
                 <span class="info-block" style="font-size: 16px; margin-top: -2px; font-family: Arial;">
                 	<a href="#">Your Site Name</a>
                 </span>
                 <span class="info-block"> 
                 	<a href="#">[Your Name Here]</a> /
                    <a href="#">Logout</a>
                 </span> 
                 <span class="info-block-final"></span>
                 <span class="info-block-rhs-final">
                 	Esto es <a href="#">Blogzf</a>
                 </span> 
            </div>
        </div>

        <div id="pageContainerWrapper">
	        <div id="pageContainer">
  				<div id="pageContent">
  					<div id="messages"><?=$this->blogzfFlashMessenger()?></div>
					<?= $this->layout()->content ?>
				</div>
			</div>
		</div>
		
        <div id="pageLeftContainerWrapper">
	        <div id="leftContainer">
  				<div id="pageLeft">
					<?= $this->menutop ?>
				</div>
			</div>
		</div>		
	</body>
</html>