<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <?= $this->headMeta() ?>
	    <?= $this->headTitle() ?>
	    <?= $this->headScript() ?>
	    <?= $this->headLink() ?>
		</head>
	
	<body class="login">
		<?=$this->layout()->content?>
	</body>
</html>