<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
    	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    	<meta name="Robots" content="index,follow"> 
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <link href="/layout/admin/css/login.css" media="screen" rel="stylesheet" type="text/css" >
        <?= $this->headScript() ?>	
	</head>
	
	<body>
		
		<div id="canvasWrapper">
			<div id="canvas">
  				<div id="pageHeaderWrapper">
  					<div id="pageHeader">
						<div id="navigationTop">
							<div id="navigationTop-sectionContent1593260" class="horizontalNavigationBar">
								<ul class="content-navigation">
									<li class="module" id="navigationTop-moduleContentWrapper3115585">
										<div id="navigationTop-moduleContent3115585">
											<a id="navigationTop-moduleLink3115585" class="" href="#"><span>Home</span></a>
										</div>
									</li>
									<li class="module" id="navigationTop-moduleContentWrapper3115586">
										<div id="navigationTop-moduleContent3115586">
											<a id="navigationTop-moduleLink3115586" class="" href="#"><span>About Blogzf</span></a>
										</div>
									</li>
								</ul>
								<br class="clearer">
							</div>
						</div>
					    <div id="bannerAreaWrapper">
					    	<div id="bannerArea">
								<h1 id="siteTitle"><a href="http://pablofmorales.blogzf.com/">Administrador de Blogzf</a></h1>
						    </div>
						</div>
					<div id="navigationBottom">
						<div id="navigationBottom-sectionContent1593260" class="horizontalNavigationBar">
							<ul class="content-navigation">
								<li class="module" id="navigationBottom-moduleContentWrapper3115585">
									<div id="navigationBottom-moduleContent3115585">
										<a id="navigationBottom-moduleLink3115585" class="" href="#"><span>Home</span></a>
									</div>
								</li>
								<li class="module" id="navigationBottom-moduleContentWrapper3115586">
									<div id="navigationBottom-moduleContent3115586">
										<a id="navigationBottom-moduleLink3115586" class="" href="#"><span>About Blogzf</span></a>
									</div>
								</li>
							</ul>
							<br class="clearer">
						</div>
					</div>
				</div>
			</div>
			<div id="pageBodyWrapper">
				<div id="pageBody">
					<div id="sidebar1Wrapper" class="verticalNavigationBarWrapper">
						<div class="iw-vnb1">
							<div class="iw-vnb2">
								<div class="iw-vnb3">
									<div class="iw-vnb4">
										<div id="sidebar1" class="verticalNavigationBar">
											<div id="sectionContent1593260" class="sectionWrapper promotedContainer">
												<div class="iw-s1">
													<div class="iw-s2">
														<div class="iw-s3">
															<div class="iw-s4">
																<div class="section">
																	<div class="caption">Top</div> 
                                                                    <ul class="content-navigation">
                                                                        <li class="module" id="moduleContentWrapper3115585">
                                                                        	<div id="moduleContent3115585">
                                                                                <a id="moduleLink3115585" class="" href="#"><span>Home</span></a>
                                                                            </div>
																		</li>
																		<li class="module" id="moduleContentWrapper3115586">
                                                                            <div id="moduleContent3115586">
                                                                                <a id="moduleLink3115586" class="" href="#"><span>About Blogzf</span></a>
                                                                            </div>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div id="sectionContent1593261" class="sectionWrapper">
												<div class="iw-s1">
													<div class="iw-s2">
														<div class="iw-s3">
															<div class="iw-s4">
																<div class="section">
														    		<div class="caption">Navigation</div> 
																	<ul class="content-navigation">
																		<li class="module" id="moduleContentWrapper3115587">
                                                                            <div id="moduleContent3115587">
                                                                            	<a id="moduleLink3115587" class="" href="http://pablofmorales.blogzf.com/links/"><span>Links</span></a>
                                                                            </div>
																		</li>
                                                                        <li class="module" id="moduleContentWrapper3115588">
                                                                        	<div id="moduleContent3115588">
                                                                        		<a id="moduleLink3115588" class="" href="http://pablofmorales.blogzf.com/login/?returnUrl=%2Fdisplay%2Fconfiguration%2FAccountPricing"><span>Login</span></a>
                                                                        	</div>
                                                                        </li>
                                                                    </ul>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
                                            <div id="sectionContent1593262" class="sectionWrapper">
                                            	<div class="iw-s1">
                                            		<div class="iw-s2">
                                            			<div class="iw-s3">
                                            				<div class="iw-s4">
                                            					<div class="section">
                                        				        <div class="content-passthrough">
                                        				        	<div id="moduleContentWrapper3115589" class="passthrough-block">
                                        				        		<div id="moduleContent3115589">
                                          									<div id="blogzf-powered">
                                            									<a onclick="this.target='new';" href="http://www.blogzf.com/?associateTag=pablofmorales"><img src="AccountPricing_files/sstiny-button.png" alt="Powered by Blogzf"></a>
                                          									</div>
                                        								</div>
                                        							</div>
                                        						</div>
                                        					</div>
                                        				</div>
                                        			</div>
                                        		</div>
                                        	</div>
                                        </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
  				
  				<div id="sidebar2Wrapper" class="verticalNavigationBarWrapper">
  					<div class="iw-vnb1">
  						<div class="iw-vnb2">
  							<div class="iw-vnb3">
  								<div class="iw-vnb4">
  									<div id="sidebar2" class="verticalNavigationBar"></div>
    							</div>
    						</div>
    					</div>
    				</div>
				</div>
			
    			<div id="contentWrapper">
    				<div id="content">
    					<div id="messages"><?=$this->blogzfFlashMessenger()?></div>
					    <?= $this->layout()->content ?>
					</div> <!-- Content -->
    			</div>
    		</div> <!-- Page Body -->
			
			<div id="pageFooterWrapper">
				<div id="pageFooter">
                    want to edit this footer? Enter structure mode by clicking the cube
                    icon in the upper right. Then press 'edit website footer' next to this
                    text. 
                </div>
           	</div>
  
  			</div>
  		</div> <!-- Canvas -->
	</body>
</html>