		<div id="login-form" class="form-body">
			<form style="margin: 0px;" method="post" name="dataform" action="<?=$this->appServer?>/admin/">
				<h2 class="document-title">Backoffice Login</h2>
				<div class="body">
                    Para entrar al backoffice usted necesita autenticarse. 
                </div>
				
            	<div class="fieldContainer">
            		<div class="fieldTitle">
                       Login: 
                       <a id="storedFieldControls" class="fieldAugmentedLink" style="display: none;" href="javascript:forgetLogin();">(forget stored information)</a>
                    </div>
                    <input tabindex="1" class="text" value="" id="username" name="username" type="text">
            	</div>
            

                <div class="fieldContainer">
                	<div class="fieldTitle">
                    	Password: 
                        <a class="fieldAugmentedLink" href="http://pablofmorales.squarespace.com/display/RecoverPassword">(I forgot my password)</a>
                	</div>
                	<input tabindex="2" class="text" id="password" name="password" type="password">
                </div>
    
                <div class="fieldContainer">
            
                <input style="float: left;" id="rememberPassword" name="rememberPassword" type="checkbox">
                <div style="float: left; margin-left: 10px;">
                	<label for="rememberPassword">Remember Password</label>
                	<div class="fieldAugmentedLink">WARNING: Password stored in plain text within browser.</div>
                </div>
    		</div>
    		<div class="fieldContainer">
    			<input tabindex="3" class="button submit-button" id="submitButton" style="margin-top: 2em;" value="Login" type="submit" />
    		</div>
    	</form>
	</div>
</div>
<script type="text/javascript">
	try{document.getElementById('username').focus();}catch(e){}
</script>
