	<div id="desktopTitlebar">
		<h1 class="applicationTitle">Mocha UI</h1>
		<h2 class="tagline">A Web Applications <span class="taglineEm">User Interface Library</span></h2>
		<div id="topNav">
			<ul class="menu-right">
				<li>Welcome <a href="#" onclick="MochaUI.notification('Do Something');return false;">Demo User</a>.</li>
				<li><a href="#" onclick="MochaUI.notification('Do Something');return false;">Sign Out</a></li>
			</ul>
		</div>
	</div>
