<div class="clearfix">
	<div id="featured">
		<div class="featured-content">
			<h3><a href="<?=$this->appServer?>/?p=41" rel="bookmark" title="Permanent Link to Puppies mark birth of commercial pet cloning">Puppies mark birth of commercial pet cloning</a></h3>
			<p>111A U.S. woman received five puppies Tuesday that were cloned from her
                                    beloved late pitbull, becoming the inaugural customer of a South Korean
                                    company that says it is the world’s first successful commercial canine
                                    cloning service.
                                 </p>
			<div class="post-meta">
				<a href="<?=$this->appServer?>/?p=41#more-41" rel="bookmark" title="Read More of Puppies mark birth of commercial pet cloning" class="btn btn-orange">Read More</a> <a href="<?=$this->appServer?>/?p=41#comments" title="Comment on Puppies mark birth of commercial pet cloning">12 Comments</a> &nbsp; | &nbsp;  Posted by <span class="orange weight-normal">FTL</span>
			</div>
		</div>
	</div>
</div>

<div class="left-content">
							
	<div class="post">
		<div class="post-date"><span class="month block">Aug </span><span class="day">28 </span></div>
		<h4><a href="<?=$this->appServer?>/?p=39" rel="bookmark" title="Permanent Link to Ocean ‘dead zones’ becoming global problem">Ocean ‘dead zones’ becoming global problem</a></h4>
		<p>Like a chronic disease spreading through the body, “dead zones” with too little oxygen for life are expanding in the world’s oceans.</p>										<div class="post-meta">
		<a href="<?=$this->appServer?>/?p=39#more-39" rel="bookmark" title="Read More of Ocean ‘dead zones’ becoming global problem" class="btn btn-pink">Read More</a> 
		<a href="<?=$this->appServer?>/?p=39#comments" title="Comment on Ocean ‘dead zones’ becoming global problem">1 Comment</a> &nbsp; | &nbsp;  Posted by 
		<span class="pink weight-normal">FTL</span>
		</div>
	</div>
											
	<div class="clearfix pagination bluegray">
		<a href="<?=$this->appServer?>/?paged=2">Previous Page</a> 
		<span class="extralarge">1 of 3</span>
	</div>
</div>
