<?php if ($this->pageCount>1): ?> 
<div class="paginationControl">
<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
  <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Anterior</a> 
<?php else: ?> 
  <!-- span class="disabled">&lt; Anterior</span--> 
<?php endif; ?> 

<!-- Numbered page links -->

<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
  	<span class="extralarge">
    <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a> 
    </span>
  <?php else: ?>
    <?= $page; ?> | 
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <a href="<?= $this->url(array('page' => $this->next)); ?>">Siguiente &gt;</a>
<?php else: ?> 
  <!-- span class="disabled">Siguiente &gt;</span-->
<?php endif; ?> 
</div> 
<?php endif; ?>