<?php if ($this->pageCount > 1) { ?>
<div class="paginationControl"><!-- Previous page link --> 
<?php if (isset($this->previous)) { ?> 
  <a href="<?=$this->url(array('page' => $this->previous));?>">&lt;
Anterior</a> 
<?php }  ?> 

<!-- Numbered page links -->

<?php
foreach ($this->pagesInRange as $page) {
if ($page != $this->current) { ?>
<span class="extralarge"> <a href="<?=$this->url(array('page' => $page));?>"><?=$page;?></a> </span>
<?php } else { ?>
<?=$page;?> | 
<?php } ?>
<?php } ?>

<!-- Next page link --> 
<?php if (isset($this->next)) { ?> 
<a href="<?=$this->url(array('page' => $this->next));?>">Siguiente &gt;</a>
<?php } ?> 
</div>
<?php } ?>