<div class="clearfix">
<div id="colors"><a
	href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=teal"
	class="color-blue">Blue</a> <a
	href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=orange"
	class="color-orange">Orange</a> <a
	href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=green"
	class="color-green">Green</a> <a
	href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=pink"
	class="color-pink">Pink</a> <a
	href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=purple"
	class="color-purple">Purple</a></div>
<div id="page-title">
<div class="page-title-content">
<h3 class="page-title"><?=$this->page->page_title;?></h3>
<div class="post-meta-single">
<p><?=$this->page->page_excerpt;?></p>
</div>
</div>
</div>
</div>
<div class="left-content">


<div class="post">
<p>
            <?=$this->page->page_content;?>
		</p>

</div>

</div>