<div class="left-content">
							
	<?php if ( count( $this->paginator )): ?>
	<?php $i=0; foreach ( $this->paginator as $post ): ?>

	<div class="post">
		<div class="post-date"><span class="month block"><?=$post->month; ?></span><span class="day"><?=$post->day; ?></span></div>
		<h4><a href="<?=$post->post_url; ?>" rel="bookmark" title="Permanent Link to "><?=$post->post_title; ?></a></h4>
		<p>
	
	    <?php if ($post->post_excerpt) {
                echo $post->post_excerpt;
	        }  else {
                echo $post->post_content;
	            
	        }
        ?>
		
		</p>
		<div class="post-meta">
    		<a href="<?=$post->post_url; ?>" rel="bookmark" title="Read More of <?=$post->post_title; ?>" class="btn btn-pink">Read More</a> 
    		<?=$this->numComments($post->num_comments); ?>&nbsp; | &nbsp;  Posted by 
    		<span class="pink weight-normal"><?=$post->username; ?></span>
		</div>
	</div>
	<?php endforeach;?>

	<?php endif; ?>

											
	<div class="clearfix pagination bluegray">
			<?= $this->paginator ?>
		<span class="extralarge">1 of 3</span>
	</div>
	
	
</div>
