<div>
	<ul class="footer-pages clearfix">
		<li class="first"><a href="<?=$this->url(array(),'default'); ?>" title="My Web Blog Home">Home</a></li>
		<li class="page_item"><a href="<?=$this->url(array('name'=>'about'),'page'); ?>" title="About">About</a></li>
		<li class="page_item "><a href="<?=$this->url(array('name'=>'contact'),'page'); ?>" title="Contact">Contact</a></li>
		<li class="page_item"><a href="<?=$this->url(array('name'=>'extras'),'page'); ?>" title="Extras">Extras</a></li>
	</ul>
	<br/>
	<p><big><strong>© Copyright My Web Blog. All rights reserved.</strong></big><br/>
			Designed by FTL <a href="http://www.freethemelayouts.com/" style="color: rgb(220, 231, 192); text-decoration: none;">Wordpress Themes</a> brought to you by <a href="http://smashingmagazine.com/" style="color: rgb(220, 231, 192); text-decoration: none;">Smashing Magazine</a>
	</p>
</div>
<a href="#top" class="btn btn-footer right">Back to Top</a>
