<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
	<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headMeta() ?>
    <?= $this->headTitle() ?>
    <?= $this->headScript() ?>
    <?= $this->headLink() ?>
	</head>
	<body>
	<a name="top"></a>
	<div id="footer-back">
		<div id="footer-bg">
			<div id="main">
				<div id="main-top">
					<div id="navigationed">
						<?= $this->layout()->menutop; ?>
					</div>
					<div id="container">
						<div id="content-back" class="clearfix"><div id="content-bottom">				
							<div id="left-col">
							
								<?= $this->layout()->content?>
							</div>
							<div id="right-col">
								<?= $this->layout()->sidebar; ?>
							</div>
						</div>
					</div>
					<div id="footer" class="clearfix">
						<?= $this->layout()->footer?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>

</html>