							<div class="clearfix">
								<div id="colors">
									<a href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=teal" class="color-blue">Blue</a>
									<a href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=orange" class="color-orange">Orange</a>
									<a href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=green" class="color-green">Green</a>
									<a href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=pink" class="color-pink">Pink</a>
									<a href="http://freethemelayouts.com/blog/wp-content/themes/colorpaper/switcher.php?style=purple" class="color-purple">Purple</a>

								</div>
								<div id="featured">
									<div class="featured-content">
																					<h3><a href="http://freethemelayouts.com/blog/?p=41" rel="bookmark" title="Permanent Link to Puppies mark birth of commercial pet cloning">Puppies mark birth of commercial pet cloning</a></h3>
												<p>A U.S. woman received five puppies Tuesday that were cloned from her beloved late pitbull, becoming the inaugural customer of a South Korean company that says it is the world&#8217;s first successful commercial canine cloning service.</p>
											<div class="post-meta">
													<a href="http://freethemelayouts.com/blog/?p=41#more-41" rel="bookmark" title="Read More of Puppies mark birth of commercial pet cloning" class="btn btn-orange">Read More</a> <a href="http://freethemelayouts.com/blog/?p=41#comments" title="Comment on Puppies mark birth of commercial pet cloning">15 Comments</a> &nbsp; | &nbsp;  Posted by <span class="orange weight-normal">FTL</span>

											</div>
									</div>
								</div>
							</div>

<div class="left-content">
							
	<?=$this->partialLoop('post/partial/post.phtml' ,  $this->paginator)?>
				
	<div class="clearfix pagination bluegray">
			<?= $this->paginator ?>
	</div>
	
	
</div>
