<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <?php 
            if ( $this->dojo()->isEnabled() ) {
                $this->dojo()->setLocalPath('/js/dojo/dojo.js');
                echo $this->dojo();
            }
        ?>		
	</head>

	<body>
		<div id="container2">
		
			<div id="header-white2">
			
				<div id="header-content">
					<div id="header-image">
						<img src="/imgs/header.gif" alt="Administrador">
					</div>
				</div>
				
				<div id="navigation">
					<?= $this->layout()->topMenu; ?>
				</div>
			</div>
			
			<div class="container">
			
				<div class="content-left">
					<div id="messages"><?=$this->easytechFlashMessenger()?></div>
					<?= $this->layout()->content ?>
				</div>
				
				<div class="content-rigth"><?= $this->layout()->sidebar; ?></div>
			</div>
			
			<p class="clear">&nbsp;</p>
			
			<div id="bottom-white2"></div>
		
		</div>

    	<div id="footer">
    	    <?= $this->layout()->footer?>
    	</div>
	</body>
</html>
