<div id="pageHeaderTitle"><?=$this->moduleName?></div>
<div id="pageBody">
	<div class="subsectionContentBlock">
		<table class="standardList" style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
			<thead>
				<tr>
                    <td>&nbsp;</td>
                    <td style="text-align: left; " nowrap="nowrap">Secciones</td>
                </tr>
            </thead>
            
            <tbody>
            	<tr>
                	<td></td>
                	<td>
                    	<a href="/admin/posts/create/">Crear Post</a>
                    </td>
                </tr>
            	<tr>
                	<td></td>
                	<td>
                    	<a href="/admin/posts/read/">Ver Posts</a>
                    </td>
                </tr>    
            	<tr>
                	<td></td>
                	<td>
                    	<a href="/admin/category/read/">Categorias</a>
                    </td>
                </tr>
            	<tr>
                	<td></td>
                	<td>
                    	<a href="/admin/tags/read/">Tags</a>
                    </td>
                </tr>
            	<tr>
                	<td></td>
                	<td>
                    	<a href="/admin/perfil/">Perfil</a>
                    </td>
                </tr>
            	<tr>
                	<td></td>
                	<td>
                    	<a href="/admin/setup/">Configuracion</a>
                    </td>
                </tr>                                                   
			</tbody>
		</table>
	</div>
</div>