<div id="login">
	<h1><a href="http://blog.pablo-morales.com/" title="Powered by blog.pablo-morales.com"><?=$this->title?></a></h1>

	<form name="loginform" id="loginform" action="authentication/login/" method="post">
		<p>
			<label>Usuario<br>
			<input name="log" id="user_login" class="input" value="" size="20" tabindex="10" type="text"></label>
		</p>
		<p>
			<label>Clave<br>
			<input name="pwd" id="user_pass" class="input" value="" size="20" tabindex="20" type="password"></label>
		</p>
		<p class="submit">
			<input name="wp-submit" id="wp-submit" value="Log In" tabindex="100" type="submit">
			<input name="redirect_to" value="http://blog.pablo-morales.com/wp-admin/" type="hidden">
			<input name="testcookie" value="1" type="hidden">
		</p>
	</form>
	
</div>

<p id="backtoblog"><a href="http://blog.pablo-morales.com/" title="Are you lost?">« Back to Blog personal de Pablo Morales</a></p>

<script type="text/javascript">
	try{document.getElementById('user_login').focus();}catch(e){}
</script>
