<?php
if ($this->pageCount) :
    ?>
<div class="paginationControl"><!-- Previous page link --> 
<?php
    if (isset($this->previous)) :
        ?> 
  <a href="<?=$this->url(array('page' => $this->previous));?>">&lt;
Anterior</a> | 

     else :
        ?> 
  <span class="disabled">&lt; Anterior</span> | 

    <?phpendif;
    ?> 

<!-- Numbered page links -->
<?php
    foreach ($this->pagesInRange as $page) :
        ?> 
  <?php
        if ($page != $this->current) :
            ?>
    <a href="<?=$this->url(array('page' => $page));?>"><?=$page;?></a> | 
  
         else :
            ?>
    <?=$page;?> | 
  
        <?phpendif;
        ?>
<?php
    endforeach;
    ?>

<!-- Next page link --> 
<?php
    if (isset($this->next)) :
        ?> 
  <a href="<?=$this->url(array('page' => $this->next));?>">Siguiente
&gt;</a>

     else :
        ?> 
  <span class="disabled">Siguiente &gt;</span>

    <?phpendif;
    ?> 
</div>

<?php endif;
?>